baseURL      = "https://resume.cmzhu.cn"
languageCode = "en-us"
title        = "朱聪明的简历"

disable404     = true
disableRSS     = true
disableSitemap = true

[params]
    author      = "Congming Zhu"
    description = "Congming Zhu's Resume"
    styles      = "styles-6.css"

    [params.profile]
        avatar  = "cmzhu.png"
        en_name = "Congming Zhu"
        name    = "廖思睿"
        tagline = "运维工程师"

    [params.contact]
        enable = true

        [[params.contact.list]]
            class = "email"
            icon  = "fa-sex"
            title = "性别/年龄: 男 25"
            url   = ""

        [[params.contact.list]]
            class = "email"
            icon  = "fa-blog"
            title = "3 年工作经验"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-envelope"
            title = "Email: zhucongming20@gmail.com"
            url   = "mailto:"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-phone"
            title = "联系电话: 15680663726"
            url   = "tel:+86 15680663726"

        [[params.contact.list]]
            class = "email"
            icon  = "fa-blog"
            title = "个人博客: blog.cmzhu.cn"
            url   = "https://github.com/cmzhublog/cmzhu.cn-blog"

[params.education]
    enable = true
    title  = "Education"

    [[params.education.list]]
        college = "成都师范学院"
        dates   = "2016.09 - 2020.06"
        degree  = "计算机科学与技术 本科"

    [[params.education.list]]
        college = "四川省南充市白塔中学"
        dates   = "2013.09 - 2016.06"
        degree  = "高中"

[params.language]
    enable = true
    title  = "Languages"

    [[params.language.list]]
        language = "英语四级"
        level    = "423分"


[params.interests]
    enable = true
    title  = "Interests"

    [[params.interests.list]]
        interest = "(1) 容器相关: Docker / K8s / Docker Compose"

    [[params.interests.list]]
        interest = "(2) Linux 基础, 了解 Centos / Debian / RockyLinux 等"

    [[params.interests.list]]
        interest = "(3) Python 编程"

    [[params.interests.list]]
        interest = "(4) 运维与监控: Ansible / Sealos / Prometheus + Grafana"

[params.summary]
    enable = true
    icon = "fa-user"
    summary = """毕业于成都师范学院, 计算机科学与技术专业,主修课程: 计算机组成原理、Python 开发；


主要技能: 

○ Kubernetes 技术栈: 熟悉 Kubernetes 容器编排技术, 包括但不限于集群部署、监控和集群日常维护

○ 容器化技术: 熟悉 Docker / Containerd  和容器化应用程序, 能够构建、优化和管理容器化工作负载

○ 持续集成/持续部署 (CI/CD): 使用 K8s 和相关工具实施 CI/CD 流程, 提高软件交付效率

○ IAAS 方面：包含 Vsan 集群、 Esxi 系统、 Vsphere Client 管理工具以及物理机的日常维护和管理
"""
    title = "Career Profile"

[params.experiences]
    enable = true
    icon   = "fa-briefcase"
    title  = "Experiences"

[[params.jobs.list]]
    company  = "成都宽邦科技有限公司"
    dates    = "2022.03 - 至今"
    details  = "在职期间参与公司PaaS 和SaaS项目的维护, 包含公司 ToC 集群的维护，同事也参与公司 ToB 集群的 Kubernetes 集群的部署和维护"
    position = "运维工程师"
[[params.jobs.list]]
    company  = "多益网络"
    dates    = "2020.06 - 2021.12"
    details  = "在职期间主要参与 IaaS 层服务器交付工作， 包括公司 **公司逻辑管控平台的维护和二开**， 参与公司自动化交付工作的建设，主要解决公司实体机、虚拟机、客户机等服务器管理和交付工作"
    position = "系统运维工程师"

[params.projects]
    enable = true
    icon   = "fa-archive"
    title  = "Projects"

    [[params.projects.list]]
        tagline = """BigQuant 人工智能量化投资交易平台(https://bigquant.com), 包括量化策略平台的开发运营和 PAAS 平台的运营维护, 产品主要为用户提供量化投研环境

主要工作: 

"""
        title = "BigQuant AI 量化平台"
        url = "https://bigquant.com/"

    [[params.projects.list]]
        tagline = """凝思安全容器系统软件(https://www.linx-info.com)是基于凝思安全操作系统完全自主研发, 具备容器隔离特性的容器产品, 同时采用了一系列的安全技术避免了现有容器技术的安全风险

主要工作:

○ 负责底层网络实现, 使用 OpenVSwitch 和 Golang 构建容器运行的网络环境, 提供网络流量控制等功能
"""
        title   = "凝思安全容器系统"
        url     = "https://www.linx-info.com"

[params.skills]
    enable = false
    icon   = "fa-rocket"
    title  = "Skills & Proficiency"

    [[params.skills.list]]
        level = "80%"
        skill = "Kubernetes & IaaS"

[params.footer]
    copyright = "蜀ICP备2022026268号-1"